name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # 

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'SohamR' # Hashnode Username
          BLOG_URL: 'https://sohamr.hashnode.dev/' # Blog URL
          COUNT: 5 # MAX Visisble
          FILE: "README.md"
          STYLE: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
