name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  render-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # This line is now using your new, powerful token
          token: ${{ secrets.METRICS_PAT }}
          user: AIMaster17
          base: activity, community
