name: GitHub 3D Profile

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 3D Profile
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: AIMaster17
          outputs_branch: main
